routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('/', function () {
//     return view('dashboard');
// });


Route::get('/', 'DashboardController@index')->name('dashboard');
 Route::get('addCopy{id}', 'BorrowingController@storeSessionCopy')->name('addCopy');
// Route::get('acerca-de', 'acercaDeController@index')->name('acerca-de');


Route::resource('prestamos', 'BorrowingController', ['parameters' => [
    'prestamos' => 'borrowing',
]]);
Route::resource('libros', 'BookController', ['parameters' => [
    'libros' => 'book',
]]);
Route::resource('clientes', 'CostumerController', ['parameters' => [
    'clientes' => 'costumer',
]]);
Route::resource('categorias', 'CategoryController', ['parameters' => [
    'categorias' => 'category',
]]);
Route::resource('editoriales', 'EditorialController', ['parameters' => [
    'editoriales' => 'editorial',
]]);
Route::resource('autores', 'AuthorController', ['parameters' => [
    'autores' => 'author',
]]);
Route::resource('ejemplares', 'CopyController', ['parameters' => [
    'ejemplares' => 'copy',
]]);

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    //
    public $timestamps = false;

    protected $fillable = ['title', 'author_id', 'category_id', 'editorial_id', 'isbn'];



    public function setNameAttribute($title)
    {
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = str_slug($title);
    }

    public function author()
    {
        return $this->belongsTo(Author::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function editorial()
    {
        return $this->belongsTo(Editorial::class);
    }

    public function copies()
    {
        return $this->hasMany(Copy::class);
    }

}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;

use Illuminate\Http\Request;
use App\Author;
use App\Category;
use App\Editorial;
use App\Http\Requests\BookStoreRequest;
use App\Http\Requests\BookUpdateRequest;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::orderBy('id', 'DESC')->get();

        return view('books.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $authors = Author::orderBy('name', 'ASC')->pluck('name', 'id');
        $categories = Category::orderBy('name', 'ASC')->pluck('name', 'id');
        $editorials = Editorial::orderBy('name', 'ASC')->pluck('name', 'id');

        return view('books.create', compact('authors', 'categories', 'editorials'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BookStoreRequest $request)
    {
        //Validar
        $book = Book::create($request->all());

        return redirect()->route('libros.index', $book->id)
            ->with('info', 'Libro registrado exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::find($id);
        return view('books.show', compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $authors = Author::orderBy('name', 'ASC')->pluck('name', 'id');
        $categories = Category::orderBy('name', 'ASC')->pluck('name', 'id');
        $editorials = Editorial::orderBy('name', 'ASC')->pluck('name', 'id');

        $book = Book::find($id);
        return view('books.edit', compact('book', 'authors', 'categories', 'editorials'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BookUpdateRequest $request, $id)
    {
        
        //Validar
        $book = Book::find($id);

        $book->fill($request->all())->save();

        return redirect()->route('libros.edit', $book->id)
            ->with('info', 'Libro actualizado con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::find($id);
        $book->delete();

        return redirect()->route('libros.index')
            ->with('info', 'Libro eliminado exitosamente.');
    }
}

resources/views/books/create.blade.php
@extends('layout') 
@section('content')
<h2 class="mb-4 mt-4">Añadir Ejemplar <i class="fas fa-book"></i> </h2>

<div class="card mb-4">
    <div class="card-header bg-white font-weight-bold">
        Campos con * son obligatorios.
    </div>
    <div class="card-body">
            {!! Form::open(['route' => 'libros.store','class' => 'form-horizontal','autocomplete' => 'off']) !!}
                        
            @include('books.partials.form')

        {!! Form::close() !!}
    </div>
</div>

@stop

resources/views/books/edit.blade.php
@extends('layout') 
@section('content')
<h2 class="mb-4 mt-4">Editar Libro <i class="fas fa-book"></i> </h2>

<div class="card mb-4">
    <div class="card-header bg-white font-weight-bold">
        Campos con * son obligatorios.
    </div>
    <div class="card-body">
        {!! Form::model($book, ['route' => ['libros.update', $book->id], 'method' => 'PUT','autocomplete' => 'off']) !!}
                        
            @include('books.partials.form')

        {!! Form::close() !!}
    </div>
</div>

@stop

resources/views/books/index.blade.php
@extends('layout') 
@section('content')

<h2 class="mb-4 mt-4">Libros <i class="fas fa-book"></i> </h2>

<a class="btn btn-success mt-2 mb-3" href="{{ route('libros.create') }}" role="button">Añadir nuevo libro <i class="fas fa-plus"></i></a>


<div class="card mb-4">
    <div class="card-body">
        <table id="table-records" class="table table-hover" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th><i class="fab fa-slack-hash"></i></th>
                    <th width="20%">Titulo</th>
                    <th>ISBN</th>
                    <th>Autor</th>
                    <th>Editorial</th>
                    <th>Categoria</th>
                    <th>Ejemplares</th>
                    <th class="actions">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($books as $book)
                <tr>
                    <td>{{ $book->id }}</td>
                    <td>{{ $book->title }}</td>
                    <td>{{ $book->isbn }}</td>
                    <td>{{ $book->author->name }}</td>
                    <td>{{ $book->editorial->name }}</td>
                    <td>{{ $book->category->name }}</td>
                    <td>{{ $book->copies->count() }}</td>

                    <td>
                        <a href="{{ route('libros.edit',$book->id)}}" class="btn btn-icon btn-dark" data-toggle="tooltip" title="Ver Ejemplares"><i class="fa fa-fw fa-bookmark"></i></i></a>
                        {{-- <a href="{{ route('libros.edit',$book->id)}}" class="btn btn-icon btn-info" data-toggle="tooltip" title="Ver Libro"><i class="fa fa-fw fa-eye"></i></a> --}}
                        <a href="{{ route('libros.edit',$book->id)}}" class="btn btn-icon btn-warning" data-toggle="tooltip" title="Editar"><i class="fa fa-fw fa-edit"></i></a>
                        <form class="d-inline" action="{{ route('libros.destroy', $book->id) }}" method="POST">
                            @csrf @method('DELETE')
                            <button type="submit" class="btn btn-icon btn-danger" data-toggle="tooltip" title="Eliminar"><i class="fa fa-fw fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

@stop
@section('scripts')
    <script>
        $(document).ready(function () {
            $('#table-records').dataTable( {
                "language": {
                "url": "{{ asset('js/Spanish.json') }}"
                 },
                 "ordering": false,
                 "pageLength": 5
            } );
        });
    </script>
@endsection