routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('/', function () {
//     return view('dashboard');
// });


Route::get('/', 'DashboardController@index')->name('dashboard');
 Route::get('addCopy{id}', 'BorrowingController@storeSessionCopy')->name('addCopy');
// Route::get('acerca-de', 'acercaDeController@index')->name('acerca-de');


Route::resource('prestamos', 'BorrowingController', ['parameters' => [
    'prestamos' => 'borrowing',
]]);
Route::resource('libros', 'BookController', ['parameters' => [
    'libros' => 'book',
]]);
Route::resource('clientes', 'CostumerController', ['parameters' => [
    'clientes' => 'costumer',
]]);
Route::resource('categorias', 'CategoryController', ['parameters' => [
    'categorias' => 'category',
]]);
Route::resource('editoriales', 'EditorialController', ['parameters' => [
    'editoriales' => 'editorial',
]]);
Route::resource('autores', 'AuthorController', ['parameters' => [
    'autores' => 'author',
]]);
Route::resource('ejemplares', 'CopyController', ['parameters' => [
    'ejemplares' => 'copy',
]]);

app/Copy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Copy extends Model
{
    public $timestamps = false;

    protected $fillable = ['book_id', 'code', 'status', 'details'];

    public function setNameAttribute($code)
    {
        $this->attributes['code'] = $code;
        $this->attributes['slug'] = str_slug($code);
    }

    public function book()
    {
        return $this->belongsTo(Book::class);
    }


    public function borrowings()
    {
        return $this->belongsToMany(Borrowing::class);
    }


}

app/Http/Controllers/CopyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Copy;
use App\Book;
use App\Http\Requests\CopyStoreRequest;
use App\Http\Requests\CopyUpdateRequest;

class CopyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $copies = Copy::orderBy('id', 'DESC')->get();

        return view('copies.index', compact('copies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $books = Book::orderBy('title', 'ASC')->pluck('title', 'id');
        return view('copies.create', compact('books'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CopyStoreRequest $request)
    {
         //Validar
        $copy = Copy::create($request->all());

        return redirect()->route('ejemplares.index', $copy->id)
            ->with('info', 'Ejemplar registrado exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $copy = Copy::find($id);
        return view('copies.show', compact('copy'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $books = Book::orderBy('title', 'ASC')->pluck('title', 'id');
        $copy = Copy::find($id);
        return view('copies.edit', compact('copy', 'books'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CopyUpdateRequest $request, $id)
    {
        //Validar
        $copy = Copy::find($id);

        $copy->fill($request->all())->save();

        return redirect()->route('ejemplares.index', $copy->id)
            ->with('info', 'Ejemplar actualizado con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $copy = Copy::find($id);
        $msjSuccess = 'Ejemplar #' . $copy->code . ' del libro ' . $copy->book->title . ' eliminado exitosamente.';
        $msjError = 'El Ejemplar #' . $copy->code . ' del libro ' . $copy->book->title . ' se encuentra en prestamo. No puede ser eliminado';

        if ($copy->status == 'PRESTADO') {
            return redirect()->route('ejemplares.index')
                ->with('error', $msjError);
        } else {
            $copy->delete();
            return redirect()->route('ejemplares.index')
                ->with('info', $msjSuccess);
        }
    }
}

resources/views/copies/create.blade.php
@extends('layout') 
@section('content')
<h2 class="mb-4 mt-4">Añadir un nuevo Ejemplar <i class="fas fa-bookmark"></i> </h2>

<div class="card mb-4">
    <div class="card-header bg-white font-weight-bold">
        Campos con * son obligatorios.
    </div>
    <div class="card-body">
            {!! Form::open(['route' => 'ejemplares.store','class' => 'form-horizontal','autocomplete' => 'off']) !!}
                        
            @include('copies.partials.form')

        {!! Form::close() !!}
    </div>
</div>

@stop

resources/views/copies/edit.blade.php
@extends('layout') 
@section('content')
<h2 class="mb-4 mt-4">Editar nuevo Ejemplar <i class="fas fa-bookmark"></i> </h2>

<div class="card mb-4">
    <div class="card-header bg-white font-weight-bold">
        Campos con * son obligatorios.
    </div>
    <div class="card-body">
        {!! Form::model($copy, ['route' => ['ejemplares.update', $copy->id], 'method' => 'PUT','autocomplete' => 'off']) !!}
                        
        @include('copies.partials.form')

        {!! Form::close() !!}
    </div>
</div>

@stop

resources/views/copies/index.blade.php
@extends('layout') 
@section('content')

<h2 class="mb-4 mt-4">Ejemplares <i class="fas fa-bookmark"></i> </h2>

<a class="btn btn-success mt-2 mb-3" href="{{ route('ejemplares.create') }}" role="button">Añadir nuevo Ejemplar <i class="fas fa-plus"></i></a>


<div class="card mb-4">
    <div class="card-body">
        <table id="table-records" class="table table-hover" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th><i class="fab fa-slack-hash"></i></th>
                    <th>Libro</th>
                    <th>Código</th>
                    <th>Status</th>
                    <th>Detalles</th>
                    <th class="actions">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($copies as $copy)
                <tr>
                    <td>{{ $copy->id}}</td>
                    <td>{{ $copy->book->title}}</td>
                    <td>{{ $copy->code}}</td>
                    <td><span class="badge @if($copy->status == 'DISPONIBLE') badge-success @else badge-danger @endif">{{ $copy->status}}</span></td>
                    <td>{{ $copy->details}}</td>
                    <td>
                        <a href="{{ route('ejemplares.edit',$copy->id)}}" class="btn btn-icon btn-warning" data-toggle="tooltip" title="Editar"><i class="fa fa-fw fa-edit"></i></a>
                        <form class="d-inline" action="{{ route('ejemplares.destroy', $copy->id) }}" method="POST">
                            @csrf @method('DELETE')
                            <button type="submit" class="btn btn-icon btn-danger" data-toggle="tooltip" title="Eliminar"><i class="fa fa-fw fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
   
@stop
@section('scripts')
    <script>
        $(document).ready(function () {
            $('#table-records').dataTable( {
                "language": {
                "url": "{{ asset('js/Spanish.json') }}"
                 },
                 "ordering": false,
                 "pageLength": 5
            } );
        });
    </script>
@endsection