routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('/', function () {
//     return view('dashboard');
// });


Route::get('/', 'DashboardController@index')->name('dashboard');
 Route::get('addCopy{id}', 'BorrowingController@storeSessionCopy')->name('addCopy');
// Route::get('acerca-de', 'acercaDeController@index')->name('acerca-de');


Route::resource('prestamos', 'BorrowingController', ['parameters' => [
    'prestamos' => 'borrowing',
]]);
Route::resource('libros', 'BookController', ['parameters' => [
    'libros' => 'book',
]]);
Route::resource('clientes', 'CostumerController', ['parameters' => [
    'clientes' => 'costumer',
]]);
Route::resource('categorias', 'CategoryController', ['parameters' => [
    'categorias' => 'category',
]]);
Route::resource('editoriales', 'EditorialController', ['parameters' => [
    'editoriales' => 'editorial',
]]);
Route::resource('autores', 'AuthorController', ['parameters' => [
    'autores' => 'author',
]]);
Route::resource('ejemplares', 'CopyController', ['parameters' => [
    'ejemplares' => 'copy',
]]);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    public $timestamps = false;

    protected $fillable = ['name'];

    public function books()
    {
        return $this->hasMany(Book::class);
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Category;
use App\Http\Requests\CategoryStoreRequest;
use App\Http\Requests\CategoryUpdateRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories = Category::orderBy('id', 'DESC')->get();

        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStoreRequest $request)
    {
        //Validar
        $category = Category::create($request->all());

        return redirect()->route('categorias.index', $category->id)
            ->with('info', 'Categoría creada exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $category = Category::find($id);
        return view('categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateRequest $request, $id)
    {
        //Validar
        $category = Category::find($id);

        $category->fill($request->all())->save();

        return redirect()->route('categorias.edit', $category->id)
            ->with('info', 'Categoría actualizada con éxito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        return redirect()->route('categorias.index')
            ->with('info', 'Categoria eliminada exitosamente.');
    }
}

resources/views/categories/create.blade.php
@extends('layout') 
@section('content')
<h2 class="mb-4 mt-4">Añadir Categoría <i class="fas fa-sad-cry"></i> </h2>

<div class="card mb-4">
    <div class="card-header bg-white font-weight-bold">
        Campos con * son obligatorios.
    </div>
    <div class="card-body">
            {!! Form::open(['route' => 'categorias.store','class' => 'form-horizontal','autocomplete' => 'off']) !!}
                        
            @include('categories.partials.form')

        {!! Form::close() !!}
    </div>
</div>

@stop

resources/views/categories/edit.blade.php
@extends('layout') 
@section('content')
<h2 class="mb-4 mt-4">Editar Categoría <i class="fas fa-sad-cry"></i> </h2>

<div class="card mb-4">
    <div class="card-header bg-white font-weight-bold">
        Campos con * son obligatorios.
    </div>
    <div class="card-body">
        {!! Form::model($category, ['route' => ['categorias.update',$category->id], 'method' => 'PUT','autocomplete' => 'off']) !!}
                        
            @include('categories.partials.form')

        {!! Form::close() !!}
    </div>
</div>

@stop

resources/views/categories/index.blade.php
@extends('layout') 
@section('content')

<h2 class="mb-4 mt-4">Categorias <i class="fas fa-sad-cry"></i> </h2>

<a class="btn btn-success mt-2 mb-3" href="{{ route('categorias.create') }}" role="button">Añadir nueva categoria <i class="fas fa-plus"></i></a>



<div class="card mb-4">
    <div class="card-body">
        <table id="table-records" class="table table-hover" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th><i class="fab fa-slack-hash"></i></th>
                    <th>Categoría</th>
                    <th class="actions">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category)
                <tr>
                    <td>{{ $category->id}}</td>
                    <td>{{ $category->name}}</td>
                    <td>
                        <a href="{{ route('categorias.edit',$category->id)}}" class="btn btn-icon btn-warning" data-toggle="tooltip" title="Editar"><i class="fa fa-fw fa-edit"></i></a>
                        <form class="d-inline" action="{{ route('categorias.destroy', $category->id) }}" method="POST">
                            @csrf @method('DELETE')
                            <button type="submit" class="btn btn-icon btn-danger" data-toggle="tooltip" title="Eliminar"><i class="fa fa-fw fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    
@stop
@section('scripts')
    <script>
        $(document).ready(function () {
            $('#table-records').dataTable( {
                "language": {
                "url": "{{ asset('js/Spanish.json') }}"
                 },
                 "ordering": false,
                 "pageLength": 5
            } );
        });
    </script>
@endsection