routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('/', function () {
//     return view('dashboard');
// });


Route::get('/', 'DashboardController@index')->name('dashboard');
 Route::get('addCopy{id}', 'BorrowingController@storeSessionCopy')->name('addCopy');
// Route::get('acerca-de', 'acercaDeController@index')->name('acerca-de');


Route::resource('prestamos', 'BorrowingController', ['parameters' => [
    'prestamos' => 'borrowing',
]]);
Route::resource('libros', 'BookController', ['parameters' => [
    'libros' => 'book',
]]);
Route::resource('clientes', 'CostumerController', ['parameters' => [
    'clientes' => 'costumer',
]]);
Route::resource('categorias', 'CategoryController', ['parameters' => [
    'categorias' => 'category',
]]);
Route::resource('editoriales', 'EditorialController', ['parameters' => [
    'editoriales' => 'editorial',
]]);
Route::resource('autores', 'AuthorController', ['parameters' => [
    'autores' => 'author',
]]);
Route::resource('ejemplares', 'CopyController', ['parameters' => [
    'ejemplares' => 'copy',
]]);

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    //
    public $timestamps = false;

    protected $fillable = ['name'];
    
    public function books()
    {
        return $this->hasMany(Book::class);
    }


}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\AuthorStoreRequest;
use App\Http\Requests\AuthorUpdateRequest;
use App\Author;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $authors = Author::orderBy('id', 'DESC')->get();

        return view('authors.index', compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('authors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AuthorStoreRequest $request)
    {
        //Validar
        $author = Author::create($request->all());

        return redirect()->route('autores.index')
            ->with('info', 'Autor creado exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $author = Author::find($id);
        return view('authors.show', compact('author'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $author = Author::find($id);
        return view('authors.edit', compact('author'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AuthorUpdateRequest $request, $id)
    {
        //Validar
        $author = Author::find($id);

        $author->fill($request->all())->save();

        return redirect()->route('autores.edit', $author->id)
            ->with('info', 'Autor actualizado con éxito');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $author = Author::find($id);
        $author->delete();

        return redirect()->route('autores.index')
            ->with('info', 'Autor eliminado exitosamente.');
    }
}

resources/views/authors/create.blade.php
@extends('layout') 
@section('content')
<h2 class="mb-4 mt-4">Añadir Autor <i class="fas fa-pen-fancy"></i> </h2>

<div class="card mb-4">
    <div class="card-header bg-white font-weight-bold">
        Campos con * son obligatorios.
    </div>
    <div class="card-body">
            {!! Form::open(['route' => 'autores.store','class' => 'form-horizontal','autocomplete' => 'off']) !!}
                        
            @include('authors.partials.form')

        {!! Form::close() !!}
    </div>
</div>

@stop

resources/views/authors/edit.blade.php
@extends('layout') 
@section('content')
<h2 class="mb-4 mt-4">Editar Autor <i class="fas fa-pen-fancy"></i> </h2>

<div class="card mb-4">
    <div class="card-header bg-white font-weight-bold">
        Campos con * son obligatorios.
    </div>
    <div class="card-body">
        {!! Form::model($author, ['route' => ['autores.update', $author->id], 'method' => 'PUT','autocomplete' => 'off']) !!}
                        
            @include('authors.partials.form')

        {!! Form::close() !!}
    </div>
</div>

@stop

resources/views/authors/index.blade.php
@extends('layout') 
@section('content')

<h2 class="mb-4 mt-4">Autores <i class="fas fa-pen-fancy"></i> </h2>


<a class="btn btn-success mt-2 mb-3" href="{{ route('autores.create') }}" role="button">Añadir nuevo autor <i class="fas fa-plus"></i></a>


<div class="card mb-4">
    <div class="card-body">
        <table id="table-records" class="table table-hover" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th><i class="fab fa-slack-hash"></i></th>
                    <th>Autor</th>
                    <th class="actions">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($authors as $author)
                <tr>
                    <td>{{ $author->id}}</td>
                    <td>{{ $author->name}}</td>
                    <td>
                        <a href="{{ route('autores.edit',$author->id)}}" class="btn btn-icon btn-warning" data-toggle="tooltip" title="Editar"><i class="fa fa-fw fa-edit"></i></a>
                        <form class="d-inline" action="{{ route('autores.destroy', $author->id) }}" method="POST">
                            @csrf @method('DELETE')
                            <button type="submit" class="btn btn-icon btn-danger" data-toggle="tooltip" title="Eliminar"><i class="fa fa-fw fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    
@stop 
@section('scripts')
    <script>
        $(document).ready(function () {
            $('#table-records').dataTable( {
                "language": {
                "url": "{{ asset('js/Spanish.json') }}"
                 },
                 "ordering": false,
                 "pageLength": 5
            } );
        });
    </script>
@endsection